[versions]
androidx-activity = "1.3.1"
accompanist-pager = "0.28.0"
androidx-material = "1.4.0"
androidx-arch-core = "2.1.0"
androidxComposeBom = "2023.01.00"
androidxComposeCompiler = "1.4.2"
androidx-compose-animation = "1.1.1"
androidx-compose-foundation = "1.2.1"
androidx-compose-runtime = "1.2.1"
androidx-core = "1.8.0"
androidx-nav-compose = "2.5.3"
androidx-paging-compose = "1.0.0-alpha18"
androidx-datastore = "1.0.0"
androidx-savedstate = "1.2.0"
androidx-vectordrawable = "1.1.0"
anvil = "2.4.4"
assertj = "3.24.2"
atomicfu = "0.18.5"
browser = "1.5.0"
com-google-dagger = "2.44.2"
com-squareup-anvil = "2.4.4"
com-squareup-okhttp3 = "4.10.0"
com-squareup-okio = "3.2.0"
constraintlayout = "2.1.4"
coroutines-test = "1.6.4"
dagger-compiler = "2.44.2"
espresso = "3.4.0"
gradle-plugin = "7.4.1"
jw-converter = "0.8.0"
kotlinx-serialization-json = "1.5.0-RC"
kotlinx-datetime = "0.4.0"
kotlinx-collections = "0.3.5"
kotlin = "1.8.10"
junit4 = "4.13.2"
junit-ext = "1.1.3"
lifecycle-runtime-ktx = "2.3.1"
io-coil-kt = "2.2.2"
retained-compose = "1.0.0"
retrofit = "2.9.0"
revealswipe = "1.0.0"
store = "5.0.0-alpha03"
swipe = "1.0.0"
room = "2.5.0"
me-saket-zoomable = "0.3.0"

[libraries]
androidx-activity-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "browser" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "androidxComposeBom" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
androidx-compose-ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3" }
androidx-material = { module = "com.google.android.material:material", version.ref="androidx-material" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-lifecycle-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle-runtime-ktx" }
androidx-nav-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidx-nav-compose" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging-compose" }
androidx-datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist-pager" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist-pager" }
atomicfu = { module = "org.jetbrains.kotlinx:atomicfu", version.ref = "atomicfu" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "io-coil-kt" }
com-google-dagger = { module = "com.google.dagger:dagger", version.ref = "com-google-dagger" }
com-jakewharton-retrofit = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "jw-converter" }
com-squareup-okhttp3-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "com-squareup-okhttp3" }
com-squareup-okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "com-squareup-okhttp3" }
com-squareup-retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines-test"}
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "dagger-compiler" }
de-charlex-compose-revealswipe = { module = "de.charlex.compose:revealswipe", version.ref = "revealswipe" }
espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
me-saket-swipe = { module = "me.saket.swipe:swipe", version.ref = "swipe" }
me-saket-zoomable = { module = "me.saket.telephoto:zoomable", version.ref = "me-saket-zoomable" }
me-saket-zoomable-coil = { module = "me.saket.telephoto:zoomable-image-coil", version.ref = "me-saket-zoomable" }
junit = { module = "junit:junit", version.ref = "junit4" }
junit-ext = { module = "androidx.test.ext:junit", version.ref = "junit-ext" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
retained-compose = { module = "dev.marcellogalhardo:retained-compose", version.ref = "retained-compose" }
store-cache = { module = "org.mobilenativefoundation.store:cache5-jvm", version.ref = "store" }
store-jvm = { module = "org.mobilenativefoundation.store:store5-jvm", version.ref = "store" }
google-firebase-bom = "com.google.firebase:firebase-bom:31.2.3"
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
kotlin-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }

[plugins]
android-application = { id = "com.android.application", version.ref = "gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "gradle-plugin" }
anvil = { id = "com.squareup.anvil", version.ref = "anvil" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
firebase-crashlytics = "com.google.firebase.crashlytics:2.9.4"
gms-googleServices = "com.google.gms.google-services:4.3.15"
